Repository mbti-dle/nyant-coin, pull requests merged in 2024-11, with the labels that each got.

#89 [Documentation] 리드미 작성
  README.md
Labels: 📚 documentation

#90 [Feature] 게임종료 소켓 이벤트 구현
  app/game/[gameId]/page.tsx
  app/result/[gameId]/page.tsx
  components/features/game/timer.tsx
  components/features/result-modal.tsx
  components/ui/modal.tsx
  server.ts
  types/game.ts
Labels: ✨ feature

#96 [Fix] 1등 플레이어 고양이 캐릭터 출력 오류 수정
  app/result/[gameId]/page.tsx
Labels: 🐛 bug

#98 [Bug] 게임 결과 텍스트 복붙하기 버그 수정
  app/result/[gameId]/page.tsx
  server.ts
Labels: 🐛 bug

#102 [Bug] 브라우저 네비게이션 시 소켓 연결이 종료되지 않는 버그
  app/game/[gameId]/page.tsx
  app/waiting/[gameId]/page.tsx
  hooks/.gitkeep
  hooks/use-socket-navigation.ts
  server.ts
Labels: 🐛 bug

#104 [Bug] 사파리 브라우저 레이아웃 이상 현상
  app/game/[gameId]/page.tsx
  app/waiting/[gameId]/page.tsx
Labels: 🐛 bug

#105 [Fix] 말풍선이 제대로 표시되지 않거나 사라지지 않는 버그 수정
  components/features/waiting/player-grid.tsx
  components/ui/cat-box.tsx
Labels: 🐛 bug

#107 [Bug] 올바른 gameId를 입력해도 새로운 방이 생성되는 오류 해결
  app/page.tsx
Labels: 🐛 bug

#108 [Fix] 메타데이터 오픈그래프 이미지 경로 문제 해결
  app/layout.tsx
Labels: 🐛 bug

#112 [Documentation] README.md 프로젝트 내용 추가
  README.md
Labels: 📚 documentation
