Repository mbti-dle/nyant-coin, pull requests merged in 2024-10, with the labels that each got.

#8 [Feature] 전반적인 폴더 구조 작업 & 데이터베이스 초기화
  .eslintrc.cjs
  .github/.gitmessage.txt
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/workflows/preview.yml
  .github/workflows/sourcery-review.yml
  .gitignore
  .husky/pre-commit
  app/api/hints/route.ts
  app/global.css
  app/layout.tsx
  app/loading.tsx
  app/page.tsx
  components/features/.gitkeep
  components/hint-item.tsx
  components/hint-list.tsx
  components/layout/.gitkeep
  components/ui/.gitkeep
  constants/.gitkeep
  hooks/.gitkeep
  lib/api/.gitkeep
  lib/api/get-hints.ts
  lib/database.ts
  lib/utils/.gitkeep
  next.config.mjs
  package-lock.json
  package.json
  public/fonts/.gitkeep
  public/images/.gitkeep
  scripts/init-db.ts
  src/app/favicon.ico
  src/app/fonts/GeistMonoVF.woff
  src/app/fonts/GeistVF.woff
  src/app/layout.tsx
  src/app/page.tsx
  styles/global.css
  tailwind.config.ts
  tsconfig.json
  types/hint.ts
Labels: ✨ feature

#12 [Docs] 깃허브 이슈 템플릿 title, name명 수정
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/refactor.yml
Labels: 📚 documentation

#22 [Setting] 테일윈드 스타일 초기 세팅
  .prettierrc
  app/global.css
  app/layout.tsx
  app/page.tsx
  package-lock.json
  package.json
  public/fonts/Galmuri9.woff2
  public/fonts/Neodgm.woff2
  tailwind.config.ts
Labels: ⚙️ settings, 💅 styling

#23 [Settings] 프로젝트에 사용할 게임 관련 이미지 파일 추가
  public/images/.gitkeep
  public/images/background-desktop-1.png
  public/images/background-desktop-2.png
  public/images/background-desktop-3.png
  public/images/background-mobile-1.png
  public/images/background-mobile-2.png
  public/images/background-mobile-3.png
  public/images/cat-1.png
  public/images/cat-2.png
  public/images/cat-3.png
  public/images/cat-4.png
  public/images/cat-404.png
  public/images/cat-5.png
  public/images/cat-6.png
  public/images/coin.png
  public/images/crown.png
  public/images/favicon/favicon.ico
  public/images/favicon/favicon.png
  public/images/fish.png
  public/images/loading.gif
  public/images/logo.png
  public/images/og.png
  public/images/paper.png
Labels: ⚙️ settings

#24 [Feature] Button 컴포넌트 추가
  components/ui/button.tsx
  package-lock.json
Labels: ✨ feature

#28 [Feature] IconButton 컴포넌트 추가
  components/ui/icon-button.tsx
Labels: ✨ feature

#30 [Feature] input 컴포넌트 추가 및 기타 설정 변경
  .eslintrc.cjs
  .github/workflows/sourcery-review.yml
  .husky/pre-commit
  .husky/pre-push
  app/layout.tsx
  components/ui/count-input.tsx
  components/ui/input.tsx
Labels: ✨ feature

#40 [Feature] catbox 컴포넌트 추가
  .eslintrc.cjs
  .github/workflows/sourcery-review.yml
  components/ui/cat-box.tsx
Labels: ✨ feature

#45 [Feat] 메타데이터에 OG 태그 추가 및 이미지 파일 이동
  app/layout.tsx
  public/app-touch-icon.png
  public/favicon.ico
  public/icon.png
  public/images/paper.png
  public/og.png
Labels: ✨ feature

#46 [Feature] 로딩 페이지 퍼블리싱
  app/loading.tsx
  tailwind.config.ts
Labels: ✨ feature, 🎨 publishing

#47 [Feature] 404 페이지 퍼블리싱
  app/not-found.tsx
  components/ui/link-button.tsx
Labels: ✨ feature, 🎨 publishing

#29 [Feature] Modal 컴포넌트 구현
  app/layout.tsx
  components/features/guide-button.tsx
  components/features/result-modal.tsx
  components/ui/modal.tsx
  constants/game.ts
  package-lock.json
  package.json
Labels: ✨ feature

#49 [Feature] 폴더 라우팅, 기본 페이지 파일 생성, 파비콘 이동 및 불필요한 파일 제거, 레이아웃 CSS 추가
  app/app-touch-icon.png
  app/favicon.ico
  app/game/[gameId]/page.tsx
  app/icon.png
  app/layout.tsx
  app/page.tsx
  app/result/[gameId]/page.tsx
  app/setup/select-days/page.tsx
  app/setup/user-info/[gameId]/page.tsx
  app/waiting/[gameId]/page.tsx
  components/ui/.gitkeep
Labels: ✨ feature

#50 [Feature] 메인페이지 퍼블리싱
  app/layout.tsx
  app/page.tsx
  components/features/guide-button.tsx
Labels: ✨ feature, 🎨 publishing

#48 [Feature] 대기방 페이지 퍼블리싱
  .gitignore
  app/global.css
  app/layout.tsx
  app/waiting/[gameId]/page.tsx
  components/features/.gitkeep
  components/features/waiting/chat-container.tsx
  components/features/waiting/chat-input.tsx
  components/features/waiting/chat-message.tsx
  components/features/waiting/game-id-copy-button.tsx
  components/features/waiting/player-grid.tsx
  components/ui/cat-box.tsx
  package-lock.json
  tailwind.config.ts
  types/.gitkeep
  types/chat.ts
Labels: ✨ feature, 🎨 publishing

#51 [Feature] 일수 선택 페이지 퍼블리싱
  app/not-found.tsx
  app/setup/select-days/page.tsx
  components/ui/radio.tsx
  constants/game.ts
Labels: ✨ feature, 🎨 publishing

#52 [feature] 게임 결과 페이지 퍼블리싱
  app/result/[gameId]/page.tsx
  components/features/guide-button.tsx
  components/ui/toast.tsx
  lib/confetti.tsx
  package-lock.json
  package.json
Labels: ✨ feature, 🎨 publishing

#53 [Feature] 게임 페이지 퍼블리싱
  app/game/[gameId]/page.tsx
  app/global.css
  components/features/game/cat-box-grid.tsx
  components/features/game/fish-coins-assets.tsx
  components/features/game/game-footer.tsx
  components/features/game/hints.tsx
  components/features/game/timer.tsx
  components/features/result-modal.tsx
  components/ui/cat-box.tsx
  components/ui/modal.tsx
  constants/game-constant.ts
  package-lock.json
  package.json
  tailwind.config.ts
  types/game.ts
Labels: ✨ feature, 🎨 publishing

#57 [Feature] 게임 ID 생성 및 중복 체크 로직 구현 (#35)
  lib/utils/generate-game-id.ts
  package-lock.json
  package.json
Labels: ✨ feature

#58 [Feature] UserInfoPage 퍼블리싱, 아바타 선택 및 뒤로가기 버튼 추가
  app/page.tsx
  app/setup/select-rounds/page.tsx
  app/setup/user-info/[gameId]/page.tsx
  app/setup/user-info/page.tsx
  components/features/waiting/player-grid.tsx
  components/ui/avatar-selector.tsx
  components/ui/count-input.tsx
  components/ui/icon-button.tsx
  components/ui/input.tsx
Labels: ✨ feature, 🎨 publishing

#68 [Feature] SocketIO 세팅
  app/game/[gameId]/page.tsx
  app/page.tsx
  components/features/game/timer.tsx
  constants/game-constant.ts
  constants/game.ts
  lib/socket.ts
  lib/utils/generate-game-id.ts
  package-lock.json
  package.json
  server.ts
  store/game.ts
  store/toast.ts
  tsconfig.json
  types/game.ts
Labels: ✨ feature

#70 [Feature] 게임 ID 유효성 검증
  app/page.tsx
  lib/utils/generate-game-id.ts
Labels: ✨ feature

#71 [Feature] 닉네임 입력 유효성 검사 및 버튼 활성화 추가
  app/setup/user-info/page.tsx
  components/ui/button.tsx
  lib/utils/nickname-validation.ts
Labels: ✨ feature

#73 [Feature] playerId uuid로 생성
  server.ts
  types/game.ts
Labels: ✨ feature

#79 [Feature] 게임 시작 소켓 이벤트 구현
  app/game/[gameId]/page.tsx
  app/waiting/[gameId]/page.tsx
  components/features/game/cat-box-grid.tsx
  components/features/waiting/chat-container.tsx
  components/features/waiting/chat-message.tsx
  components/features/waiting/player-grid.tsx
  constants/game.ts
  public/images/Error.svg
  server.ts
  store/chat.ts
  types/chat.ts
Labels: ✨ feature

#80 [Feature] 데이터베이스 초기화
  scripts/init-db.ts
  types/game.ts
Labels: ✨ feature

#81 [Feature] 대기실 채팅 기능 socket 이벤트 구현
  app/waiting/[gameId]/page.tsx
  components/features/waiting/chat-container.tsx
  components/features/waiting/chat-input.tsx
  components/features/waiting/chat-message.tsx
  components/features/waiting/chat-notice.tsx
  constants/.gitkeep
  constants/chat.ts
  server.ts
  store/chat.ts
  types/chat.ts
Labels: ✨ feature

#82 [Feature] 생선 거래 기능 구현
  app/game/[gameId]/page.tsx
  components/features/game/game-footer.tsx
  components/features/waiting/player-grid.tsx
  components/ui/cat-box.tsx
  server.ts
  tsconfig.server.json
  types/game.ts
Labels: 🐛 bug, ✨ feature

#83 [Feature] 유효성 검사 실패 시 input 포커싱
  app/page.tsx
  app/setup/user-info/page.tsx
  components/ui/count-input.tsx
  components/ui/input.tsx
Labels: ✨ feature

#86 [Styling] 배경 이미지 변경 및 버튼 호버 효과 적용
  app/page.tsx
  app/setup/select-rounds/page.tsx
  app/setup/user-info/page.tsx
  components/features/game/game-footer.tsx
  components/features/guide-button.tsx
  components/features/waiting/game-id-copy-button.tsx
  components/ui/avatar-selector.tsx
  components/ui/button.tsx
  components/ui/link-button.tsx
  public/images/background-desktop-1.png
  public/images/background-mobile-1.png
  tailwind.config.ts
Labels: 💅 styling

#87 [Feature] 다음 날 정보 전송 socket 이벤트 구현 (가격, 힌트)
  app/game/[gameId]/page.tsx
  components/features/game/game-footer.tsx
  components/features/game/hints.tsx
  components/ui/button.tsx
  components/ui/link-button.tsx
  constants/game.ts
  lib/api/.gitkeep
  lib/api/hints.ts
  lib/utils/.gitkeep
  lib/utils/game.ts
  scripts/init-db.ts
  server.ts
  types/game.ts
Labels: ✨ feature
