Repository mbti-dle/nyant-coin, pull requests merged in 2025-01, with the labels that each got.

#126 [Settings] Husky를 Lefthook으로 교체
  .husky/pre-commit
  lefthook.yml
  package-lock.json
  package.json
Labels: ⚙️ settings

#127 [Refactor] server.ts 파일 로직 분리
  .github/workflows/preview.yml
  .husky/_/pre-commit
  .husky/_/pre-push
  .husky/_/prepare-commit-msg
  package-lock.json
  package.json
  server.ts
  server/game/handlers.ts
  server/game/player.ts
  server/game/store.ts
  server/game/timer.ts
  server/index.ts
  server/socket/config.ts
  tsconfig.json
  tsconfig.server.json
Labels: 🔧 refactor

#131 [Settings] SEO 최적화 작업
  .github/workflows/cleanup-preview.yml
  .github/workflows/preview.yml
  app/layout.tsx
  app/robots.ts
  app/sitemap.ts
Labels: ⚙️ settings

#136 [Feat] 검색 메타 태그 추가
  app/layout.tsx
Labels: ✨ feature

#138 [Bug/Refactor] 모바일/데스크톱 전환 시 소켓 연결 해제 및 lint-staged 설정 리팩토링
  hooks/use-socket-navigation.ts
  lib/utils/device.ts
  package.json
Labels: 🐛 bug, 🔧 refactor

#140 [Feat] Toast 상태 관리에 requestAnimationFrame 적용 및 안정성 개선
  store/toast.ts
Labels: 🐛 bug

#146 [Refactor] 소켓 연결 방식을 Context API로 변경
  app/game/[gameId]/page.tsx
  app/layout.tsx
  app/page.tsx
  app/result/[gameId]/page.tsx
  app/setup/user-info/page.tsx
  app/waiting/[gameId]/page.tsx
  components/features/chat/chat-container.tsx
  components/features/chat/chat-input.tsx
  components/features/game/timer.tsx
  components/provider/socket-provider.tsx
  hooks/use-socket-navigation.ts
  hooks/use-socket.ts
  lib/socket.ts
Labels: 🔧 refactor
